name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_versions: [ '1.18', '1.19', '1.20', '1.21', '1.22' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go_versions }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_versions }}
      - run: go version
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./... -cover