name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_versions: [ '1.18', '1.19', '1.20', '1.21', '1.22' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go_versions }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_versions }}
      - run: go version
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      
      # Static code analysis
      - name: Look for suspicious constructs
        run: go vet ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Perform static code analysis
        run: staticcheck ./...
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Lint the code
        run: golint ./...

      # Run unit tests
      - name: Test
        run: go test -v ./... -cover